export const CONFIG = {
  MAX_MOVE_CHANGE_PERCENT: 0.01,
  VISION_DISTANCE: 400,
  GAME_LOOP_MS: 10,
  GLOBAL_HEIGHT: 1200,
  GLOBAL_WIDTH: 1200,
  ACCELERATION_FACTOR: 1.5,
  MAX_PLAYERS: 8,
  QUEUE_TIME: 2,
  RETRY_TIME: 10
}