---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
  namespace: oneball
spec:
  dnsNames:
    - oneball.onepoint.game
    - wss.oneball.onepoint.game
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 4096
  secretName: oneball-tls
  subject:
    organizationalUnits:
      - provoly
