---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app
  namespace: oneball
spec:
  dnsNames:
    - oneball.provoly.net
    - wss.oneball.provoly.net
  issuerRef:
    kind: ClusterIssuer
    name: issuer-gandi-provoly-dns
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 4096
  secretName: oneball-tls
  subject:
    organizationalUnits:
      - provoly
