---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: oneball
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cinder-high-speed
